// ──────────────────────────────────────────────────────────────────────────────
// models/widget-info.ts
//
// Purpose
//   Metadata representation of UI widgets parsed from Angular templates.
//   Used by analyzers/builders to reason about event flow, validation,
//   and user-interaction coverage.
//
// Exposed types
//   - WidgetInfo      : static metadata for a single widget (DOM element,
//                       directive, or third-party component)
//   - WidgetPathInfo  : helper path descriptor linking widgets to components
//
// Notes
//   • A "widget" denotes any interactive or structural UI element within
//     an Angular template — including native HTML tags and custom components.
//   • The structure is hierarchical: `children` may contain nested WidgetInfo
//     objects discovered inside this widget's template subtree.
//   • `events` captures normalized event types mapped to handler method names.
//   • `originalNode` references the Angular AST node for traceability.
// ──────────────────────────────────────────────────────────────────────────────

import { TmplAstNode } from "@angular/compiler";
import { NavEventType, UserEventType } from "./event-info.js";

/**
 * Static metadata for a UI widget discovered in an Angular template.
 *
 * A widget may be:
 *  • a native DOM element (e.g., `<input>`, `<button>`, `<form>`)
 *  • a directive-host element
 *  • a third-party or custom Angular component tag
 */
export interface WidgetInfo {
    /**
    * Globally unique, namespaced widget ID, emitted as:
    *   "<componentSelector>__<LOCAL>"
    * where <LOCAL> is generated by the WidgetIDGenerator:
    *   • contextual/binding/text → "<TAG>__<base>__<uuid8>"
    *   • symbolic fallback       → "<TAG>" or "<TAG>__<n>"
    */
    id: string;

    /**
    * The widget's tag or element type (e.g., `"input"`, `"button"`, `"app-card"`).
    * For Angular components, this will correspond to the component selector.
    */
    type: string;

    /**
    * Mapping of standardized event type → handler method name.
    *
    * - Keys come from {@link UserEventType} or {@link NavEventType}.
    * - Values are the names of methods bound in the template (if any).
    *
    * Example:
    * ```ts
    * { click: "onSave", input: "onInputChange" }
    * ```
    */
    events: Record<UserEventType | NavEventType, string | undefined>;

    /**
    * Raw HTML attributes or Angular directive inputs present on this widget.
    * Example:
    * ```ts
    * { placeholder: "Enter name", value: "John" }
    * ```
    */
    attributes?: Record<string, any>;

    /**
    * Validation rule names applied to this widget.
    * Derived from Angular form directives or native attributes
    * (e.g., `["required", "minLength"]`).
    */
    validationRules?: string[];

    /**
    * Whether this widget triggers a form submission.
    * Typically `true` for `<button type="submit">` elements.
    */
    triggersFormSubmission?: boolean;

    /**
    * Child widgets nested inside this widget's template subtree.
    * Used to reconstruct the full UI hierarchy for a component.
    */
    children?: WidgetInfo[];

    /**
    * The original Angular compiler AST node (`TmplAstElement`, `TmplAstTemplate`, etc.)
    * from which this widget was derived. Retained for deep analyses requiring
    * source spans, directive metadata, or structural context.
    */
    originalNode?: TmplAstNode,
}

/**
 * Identifies the hierarchical path of a widget inside its parent component.
 *
 * Example:
 * ```ts
 * { componentId: "AppFormComponent", widgetPath: ["form", "input#username"] }
 * ```
 */
export type WidgetPathInfo = {
    /** The component (by unique ID) that owns this widget hierarchy. */
    componentId: string;

    /** Ordered list of widget IDs or selectors representing the path to the target widget. */
    widgetPath: string[]
};